global:
  imagePullSecrets: []

  image:
    repository: stefanprodan/podinfo
    pullPolicy: IfNotPresent
    tag: 6.3.3

  channel: stable

app:
  enabled: true

  replicas: 1

  terminationGracePeriodSeconds: 30

  rollingUpdate:
    maxSurge: 30%
    maxUnavailable: 1

  resources:
    limits:
      cpu: 110m
      memory: 100Mi
    requests:
      cpu: 110m
      memory: 100Mi

  ingress:
    enabled: false
