global:
  imagePullSecrets: []

  image:
    repository: stefanprodan/podinfo
    pullPolicy: IfNotPresent
    tag: 6.3.3

  channel: stable

app:
  enabled: true

  replicas: 1

  deploymentLabels:
    critical: "true"

  terminationGracePeriodSeconds: 30

  rollingUpdate:
    maxSurge: 30%
    maxUnavailable: 2

  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 100Mi

  ingress:
    enabled: false
