apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stg-podinfo
spec:
  destination:
    name: in-cluster
  project: default
  source:
    repoURL: https://github.com/ardikabs/argocd-local
    targetRevision: HEAD
    path: apps/podinfo/staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true # disables resource validation (equivalent to 'kubectl apply --validate=false') ( true by default ).
      - PrunePropagationPolicy=foreground # Supported policies are background, foreground and orphan.
      - PruneLast=true # Allow the ability for resource pruning to happen as a final, implicit wave of a sync operation
      - ApplyOutOfSync=true
      - RespectIgnoreDifferences=true
    ignoreDifferences:
      - group: apps
        kind: Deployment
        jsonPointers:
          - /spec/template/metadata/annotations/kubectl.kubernetes.io~1restartedAt
